# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-24 14:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportConstruction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(default='', max_length=30)),
                ('companyName', models.CharField(default='', max_length=50)),
                ('contractNumber', models.CharField(blank=True, default='', max_length=30)),
                ('endDate', models.CharField(default='', max_length=20)),
                ('startDate', models.CharField(blank=True, default='', max_length=20)),
                ('duration', models.CharField(default='', max_length=20)),
                ('budgets', models.IntegerField(default=0)),
                ('engineerName', models.CharField(blank=True, default='', max_length=30)),
                ('provice', models.CharField(default='', max_length=30)),
                ('district', models.CharField(default='', max_length=30)),
                ('subDistrict', models.CharField(default='', max_length=30)),
                ('villageNo', models.CharField(blank=True, default='', max_length=10)),
                ('street', models.CharField(blank=True, default='', max_length=30)),
                ('etc', models.CharField(blank=True, default='', max_length=100)),
                ('latitude', models.FloatField(default=0)),
                ('longitude', models.FloatField(default=0)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportContruction', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('create',),
            },
        ),
    ]
