# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-06 18:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oldConstruction', '0005_auto_20161206_1847'),
    ]

    operations = [
        migrations.RenameField(
            model_name='oldconstruction',
            old_name='status',
            new_name='status_construction',
        ),
    ]
