# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-16 15:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OldConstruction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(default='', max_length=100)),
                ('companyName', models.CharField(default='', max_length=100)),
                ('contractNumber', models.CharField(blank=True, default='', max_length=100)),
                ('endDate', models.CharField(default='', max_length=100)),
                ('startDate', models.CharField(blank=True, default='', max_length=100)),
                ('duration', models.CharField(default='', max_length=100)),
                ('budgets', models.IntegerField(default=0)),
                ('engineerName', models.CharField(blank=True, default='', max_length=100)),
                ('provice', models.CharField(default='', max_length=100)),
                ('district', models.CharField(default='', max_length=100)),
                ('subDistrict', models.CharField(default='', max_length=100)),
                ('villageNo', models.CharField(blank=True, default='', max_length=10)),
                ('street', models.CharField(blank=True, default='', max_length=100)),
                ('etc', models.CharField(blank=True, default='', max_length=100)),
                ('latitude', models.FloatField(default=0)),
                ('longitude', models.FloatField(default=0)),
            ],
            options={
                'ordering': ('create',),
            },
        ),
        migrations.CreateModel(
            name='ReportConstruction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(default='', max_length=100)),
                ('companyName', models.CharField(default='', max_length=100)),
                ('contractNumber', models.CharField(blank=True, default='', max_length=100)),
                ('endDate', models.CharField(default='', max_length=100)),
                ('startDate', models.CharField(blank=True, default='', max_length=100)),
                ('duration', models.CharField(default='', max_length=100)),
                ('budgets', models.IntegerField(default=0)),
                ('engineerName', models.CharField(blank=True, default='', max_length=100)),
                ('provice', models.CharField(default='', max_length=100)),
                ('district', models.CharField(default='', max_length=100)),
                ('subDistrict', models.CharField(default='', max_length=100)),
                ('villageNo', models.CharField(blank=True, default='', max_length=10)),
                ('street', models.CharField(blank=True, default='', max_length=100)),
                ('etc', models.CharField(blank=True, default='', max_length=100)),
                ('latitude', models.FloatField(default=0)),
                ('longitude', models.FloatField(default=0)),
            ],
            options={
                'ordering': ('create',),
            },
        ),
    ]
